import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/component/header/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
<div className="gap-4 border">
        <div className="mb-5">
          < Header />

        </div>
        
        
        <div className="m-auto w-11/12 border   ">
        {children}

        </div>

</div>
        </body>
    </html>
  );
}
