import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/component/header/nav";
import { Footer } from "@/component/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-dvh border">
      <body className="h-dvh">
<div className="gap-4 h-dvh border">
        
        <div className="mb-5 h-dvh">
          <div className="w-11/12 h-dvh m-auto">
             <h1 className="text-4xl">Nathan Vallan peinture</h1>
             <div className='w-full flex  '>
              <h4 className=' '>connexion</h4>
             </div>
        
        <div className="m-auto w-full border cadre relative overflow-hidden flex  ">

          <div className="nav"> 
          < Header />

          </div>

          <div className="flex">
           
            <div className=" w-full h-full absolute right-0 z-20 ">
          
        {children}

              

            </div>
            

          </div>

        </div>
        </div>


          </div>
        {/* <div className="mb-5 mt-96">
          < Footer />

        </div> */}

</div>
        </body>
    </html>
  );
}
